# Wayland sanity
vo=gpu-next
gpu-context=wayland

# Fix washed-out colors
icc-profile-auto=no
target-colorspace-hint=no
tone-mapping=clip
hdr-compute-peak=no

# Force full color range
video-output-levels=full

# Stop gamma weirdness on fullscreen
gamma-auto=no
